package com.axa.portal.esp.services.SB.model.impl;

import com.axa.portal.esp.services.SB.model.cmmCache;
import com.axa.portal.esp.services.SB.service.cmmCacheLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the cmmCache service. Represents a row in the &quot;cmm_cmmCache&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cmmCacheImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see cmmCacheImpl
 * @see com.axa.portal.esp.services.SB.model.cmmCache
 * @generated
 */
public abstract class cmmCacheBaseImpl extends cmmCacheModelImpl
    implements cmmCache {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a cmm cache model instance should use the {@link cmmCache} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            cmmCacheLocalServiceUtil.addcmmCache(this);
        } else {
            cmmCacheLocalServiceUtil.updatecmmCache(this);
        }
    }
}
